### ISSUE TITLE
Great work. Can you release the code fine-tuning the models while the alignment region is frozen?

### ISSUE THREAD

**Issue by YichenBC** [boyiwei/alignment-attribution-code#4]

**Comment by boyiwei** [comment]
Hi, I have updated our code for freezing the alignment region when doing fine-tuning. To be more precisely, our approach is first do vanilla fine-tuning following the settings in https://github.com/LLM-Tuning-Safety/LLMs-Finetuning-Safety, then rewind the weight in the alignment region to zero. For the checkpoints of fine-tuning the model with 10/50/100 adversarial examples, please refer to https://huggingface.co/boyiwei/pure_bad_10-7b-full, https://huggingface.co/boyiwei/pure_bad_50-7b-full, https://huggingface.co/boyiwei/pure_bad_100-7b-full. If you have any problems in implementation please feel free to let me know

**Comment by YichenBC** [comment]
Thank you for the detailed update. I really appreciate the clear steps on fine-tuning, which are very helpful for my project.

**Comment by renjie3** [comment]
Hi, thanks for your great job! Can I ask whether these checkpoints are before or after rewinding?

 https://huggingface.co/boyiwei/pure_bad_10-7b-full, https://huggingface.co/boyiwei/pure_bad_50-7b-full, https://huggingface.co/boyiwei/pure_bad_100-7b-full.

**Comment by boyiwei** [comment]
The checkpoints are got after rewinding.
