### ISSUE TITLE
Perplexity is way off for Llama2 models

### ISSUE THREAD

**Issue by slardar94** [boyiwei/alignment-attribution-code#5]
Congratulations on your work! I tried running your code using the command  below with no values modified. I downloaded fresh llama2-7b-chat-hf and llama2-7b-hf but still there is problem

`model="llama2-7b-chat-hf"
method="wanda"
type="unstructured"
suffix="weightonly"
save_dir="out/$model/$type/${method}_${suffix}/align/"

python main.py \
    --model $model \
    --prune_method $method \
    --prune_data align \
    --sparsity_ratio 0.5 \
    --sparsity_type $type \
    --neg_prune
    --save $save_dir \
    --eval_zero_shot \
    --eval_attack \
    --save_attack_res`
    But I'm getting **perplexity as 199542.59375**
    
torch 2.1.0
transformers 4.35.2
accelerate 0.24.1
\# of gpus:  1
Disentangle: True

Can you help me out?

**Comment by boyiwei** [comment]
Hi, please refer to the correct hyperparameter settings mentioned in our paper. The hyperparameter setting in README is for demonstration purposes only. Based on the setting you provided, you are pruning 50% of weights with top-down pruning. Of course the model will collapse. If you want to replicate the results in our paper please use set difference method when pruning neurons.
